config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "posts#index"

  devise_for :users
  patch '/users/update_my_posts', to: 'users#update_my_posts', as: :update_my_posts_user

  resources :posts, except: %i[show] do
    resources :pictures, only: %i[create destroy]
    resources :comments, only: %i[create destroy update]
    resources :subscriptions, only: %i[create destroy]
    post :show, on: :member
  end

  resources :users, only: %i[show] do
    resources :friendships, only: %i[create destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :post_hashtags
  has_many :posts, through: :post_hashtags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :post_hashtags
  has_many :hashtags, through: :post_hashtags
  has_one_attached :image

  validates :description, :title, presence: true
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
  belongs_to :post
end

app/models/post_hashtag.rb
class PostHashtag < ApplicationRecord
  belongs_to :post
  belongs_to :hashtag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user_can_edit?

  def current_user_can_edit?(model)
    user_signed_in? &&
      (model&.user == current_user || (model.try(:event).present? && model.event.user == current_user))
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, except: %i[edit]
  before_action :set_comment, only: %i[destroy update]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to root_path, notice: 'Comment was successfully created.'
    else
      render root_path, alert: 'something went wrong'
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to root_path, notice: 'Комментарий успешно обновлен'
    else
      redirect_to root_path, alert: 'Не удалось обновить комментарий'
    end
  end

  def destroy
    if current_user_can_edit?(@comment)
      @comment.destroy
      message = { notice: I18n.t("controllers.comments.destroyed") }
    else
      message = { alert: I18n.t("controllers.comments.error") }
    end

    redirect_to root_path, message
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActiveStorage::SetCurrent
  before_action :authenticate_user!, except:  %i[index show]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = params[:my_posts] == 'true' && user_signed_in? ? current_user.posts : Post.all
    @posts = @posts.joins(:hashtags).where(hashtags: { name: params[:hashtag] }) unless params[:hashtag].nil?
    @posts = @posts.order(created_at: :desc).page(params[:page]).per(4)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      hashtags = @post.description.scan(/#\w+/).map{ |tag| tag.gsub("#", "") }
      hashtags.each do |tag|
        hashtag = Hashtag.find_or_create_by(name: tag)
        PostHashtag.create(post: @post, hashtag: hashtag)
      end
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new, alert: 'Post not created'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      @post.post_hashtags.destroy_all
      hashtags = @post.description.scan(/#\w+/).map{ |tag| tag.gsub("#", "") }
      hashtags.each do |tag|
        hashtag = Hashtag.find_or_create_by(name: tag)
        PostHashtag.create(post: @post, hashtag: hashtag)
      end
      redirect_to root_path, notice: 'Post was successfully updated.'
    else
      render :edit, alert: 'Post not updated'
    end
  end

  def destroy
    if current_user_can_edit?(@post)
      @post.destroy
      redirect_to root_path, notice: 'Post was successfully destroyed.', turbolinks: false
    else
      redirect_to root_path, alert: 'You cant do this', turbolinks: false
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description, :image)
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update_my_posts
    current_user.update(my_posts: params[:my_posts])
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="media border-top p-3">
  <div class="media-body col-md-10 d-inline-block mx-2">
    <p><%= comment.body %></p>
    <p><small><%= l(comment.created_at, format: :short) %></small></p>
  </div>
  <% if current_user_can_edit?(comment) %>
    <div class="d-flex">
      <button type="button" class="btn btn-secondary fa fa-pencil mx-2" data-bs-toggle="modal" data-bs-target="#edit-comment-modal-<%= comment.id %>"></button>
      <%= button_to '', post_comment_path(comment.post, comment), method: :delete, class: "btn btn-danger fa fa-trash mx-2",
                    form: { data: { turbo_confirm: I18n.t("actions.confirmation") } } %>
    </div>
  <% end %>
</div>
<%= render partial: "comments/edit_modal", locals: { comment: comment, post: comment.post } %>

app/views/comments/_edit_modal.html.erb
<div class="modal fade" id="edit-comment-modal-<%= comment.id %>" tabindex="-1" aria-labelledby="editCommentModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for [post, comment], data: {turbo: false} do |form| %>
        <div class="form-group my-3 text-center">
          <%= form.label :body, I18n.t("form.comment.body") %>
          <%= form.text_area :body, class: "form-control" %>
        </div>
        <%= form.submit I18n.t("form.comment.submit"), class: "btn btn-warning mt-2 mb-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [post, comment], data: {turbo: false} do |form| %>
  <div class="form-group my-3 text-center">
    <%= form.label :body, I18n.t("form.comment.body") %>
    <%= form.text_area :body, class: "form-control" %>
  </div>
  <%= form.submit I18n.t("form.comment.submit"), class: "btn btn-warning mt-2 mb-3" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Buddy" %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body class="bg-light">
<header class="p-3 bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <div class="text-center">
        <h2 class="text-warning mb-0">Buddy</h2>
      </div>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to "Home", root_path, class: "nav-link px-2 text-warning" %></li>
      </ul>

      <div class="d-flex justify-content-around">
        <% if user_signed_in? %>
          <p class="mb-0"><%= link_to I18n.t("links.new_post"), new_post_path, class: "btn btn-warning me-2" %></p>
          <p class="mb-0"><%= button_to I18n.t("links.destroy_user_session"), destroy_user_session_path, method: :delete, class: "btn btn-danger" %></p>
        <% else %>
          <p class="mb-0"><%= link_to I18n.t("links.new_user_session"), new_user_session_path, class: "btn btn-outline-light me-2 mb-0" %></p>
          <p class="mb-0"><%= link_to I18n.t("links.new_user_registration"), new_user_registration_path, class: "btn btn-warning mb-0" %></p>
        <% end %>
      </div>
    </div>
  </div>
</header>


<div class="container bg-white p-3">
  <div class="row">
    <div class="col-lg-12">
      <% if flash[:notice].present? %>
        <div class="alert alert-success alert-dismissible fade show d-flex justify-content-between align-items-center" role="alert" id="flash-notice">
          <p class="mb-0 text-start"><%= notice %></p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
        </div>
        <script>
            setTimeout(function() {
                $('#flash-notice button').click();
            }, 5000);
        </script>
      <% end %>
      <% if flash[:alert].present? %>
        <div class="alert alert-danger alert-dismissible fade show d-flex justify-content-between align-items-center" role="alert" id="flash-notice">
          <p class="mb-0 text-start"><%= alert %></p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
        </div>
        <script>
            setTimeout(function() {
                $('#flash-notice button').click();
            }, 5000);
        </script>
      <% end %>
      <%= yield %>
    </div><!--/span-->
  </div><!--/row-->
</div> <!-- /container -->
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, html: { multipart: true }, data: { turbo: false } do |form| %>

    <div class="form-group">
      <%= form.label :image, I18n.t("form.picture.photo") %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

  <div class="form-group mt-4">
    <%= form.label :title, I18n.t("form.post.title") %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group mt-4">
    <%= form.label :description, I18n.t("form.event.description") %>
    <%= form.text_area :description, { class: "form-control", rows: 5 } %>
  </div>

  <div class="actions mt-4">
    <%= form.submit I18n.t("form.event.submit"), class: "btn btn-primary" %>
    <%= link_to I18n.t("links.back"), :back, class: "btn btn-warning ms-2" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var cardText = document.querySelector('.card-text-number-<%= counter %>');
        var cardLink = document.querySelector('.card-link-number-<%= counter %>');
        var originalText = cardText.innerText;
        var maxLength = 150;

        if (originalText.length > maxLength) {
            var truncatedText = originalText.substring(0, maxLength) + '...';
            cardText.innerHTML = truncatedText;
        }

        cardLink.addEventListener('click', function (event) {
            event.preventDefault();
            cardText.innerHTML = originalText;
            cardLink.style.display = 'none';
        });
    });
</script>

<div class="card-body border-bottom">
  <h5 class="card-title text-center"><%= post.title %></h5>
  <div class="card-text">
    <%= image_tag post.image.url, class: 'picture_box my-3' if post.image.attached? %>
    <p>
    <div class="d-inline card-text-number-<%= counter %>"><%= simple_format post.description %></div>
    <% if post.description.length > 150 %>
      <a href="#" class="card-link-number-<%= counter %>">Показать полностью</a>
    <% end %>
    </p>
  </div>
  <div>
    <small>
      <% post.hashtags.each do |tag| %>
        <%= link_to "##{tag.name}", params[:my_posts] == 'true' ? root_path(hashtag: tag.name, my_posts: true) : root_path(hashtag: tag.name), class: 'text-decoration-none' %>
      <% end %>
    </small>
  </div>
  <div class="d-flex">
    <button class="btn btn-primary fa fa-comments mx-2" type="button" data-bs-toggle="collapse" data-bs-target="#comments-section-<%= counter %>" aria-expanded="false" aria-controls="comments-section-<%= counter %>"></button>
    <% if current_user_can_edit?(post) %>
      <%= link_to '', edit_post_path(post), class: 'btn btn-secondary fa fa-pencil mx-2' %>
      <%= button_to '', post, method: :delete, form: { data: { turbo_confirm: I18n.t("actions.confirmation") } }, class: 'btn btn-danger fa fa-trash mx-2' %>
    <% end %>
  </div>
  <div class="collapse" id="comments-section-<%= counter %>">
    <% new_comment = post.comments.build %>
    <% if user_signed_in? %>
      <%= render partial: "comments/form", locals: { comment: new_comment, post: post } %>
    <% end %>
    <%= render partial: "comments/comment", collection: post.comments.except(new_comment) %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1 class="text-center mb-5">
  <%= I18n.t("titles.post.edit") %>
</h1>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<div class="row buffer-bottom">
  <% if user_signed_in? %>
    <div class="d-flex justify-content-end">
      <% if params[:my_posts] == 'true' %>
        <%= link_to 'Показать все посты', root_path, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to 'Показать только мои посты', root_path(my_posts: true), class: 'btn btn-primary' %>
      <% end %>
    </div>
  <% end %>
  <div class="col-md-10 mx-auto">
    <% @posts.each_with_index do |post, index| %>
      <%= render partial: "posts/post", locals: { post: post, counter: index + 1 } %>
    <% end %>
  </div>
  <%= paginate @posts, remote: true %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center mb-5">
  <%= I18n.t("titles.post.new") %>
</h1>
<%= render "form", post: @post %>